name: Deploy resources

on:
  workflow_call

jobs:
  deploy-terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build files artefact
        uses: actions/download-artifact@v4
        with:
          name: built files
          path: ./.terraform

      - name: Create temporary AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.CICD_IAM_ROLE }}
          aws-region: ${{ env.CICD_AWS_REGION }}

      - name: Perform git checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Perform Terraform Plan
        run: terraform plan -no-color

      - name: Perform Terraform Apply
        run: terraform apply -auto-approve -no-color